### ISSUE TITLE
Problème de templating dans la partie 'configuration' du mode Admin

### ISSUE THREAD

**Issue by ptaillard** [cfpio/callForPapers#117]
Je viens de me rendre compte d'une régression concernant un pb de templating ngTranslate (il me semble ;-)) dans la partie 'configuration' du mode Admin.

Ci-dessous l'erreur de la console:
The specified value "{{ config.start | date: 'yyyy-MM-dd' }}" does not conform to the required format, "yyyy-MM-dd".
jquery.js:5322 The specified value "{{ config.decision | date: 'yyyy-MM-dd' }}" does not conform to the required format, "yyyy-MM-dd".
jquery.js:5322 The specified value "{{ config.release | date: 'yyyy-MM-dd' }}" does not conform to the required format, "yyyy-MM-dd".
jquery.js:5045 The specified value "{{ config.start | date: 'yyyy-MM-dd' }}" does not conform to the required format, "yyyy-MM-dd".
jquery.js:5045 The specified value "{{ config.decision | date: 'yyyy-MM-dd' }}" does not conform to the required format, "yyyy-MM-dd".
jquery.js:5045 The specified value "{{ config.release | date: 'yyyy-MM-dd' }}" does not conform to the required format, "yyyy-MM-dd".
angular.js:11655 TypeError: e.toDate is not a function
    at new <anonymous> (https://agile-grenoble.cfp.io/scripts/scripts-460d5966.js:10:196)
    at i (https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:1:18005)
    at Object.o [as instantiate](https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:1:18097)
    at https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:2:6867
    at https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:24:23845
    at oe (https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:2:3741)
    at b (https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:1:29840)
    at s (https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:1:25663)
    at https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:1:25159
    at f (https://agile-grenoble.cfp.io/scripts/modules-3d21d7dd.js:24:23053) <ui-view class="ng-scope">

**Comment by vferries** [comment]
Vous pouvez fermer cette issue du coup.
