### ISSUE TITLE
Multiple exceptions when event has no config at all

### ISSUE THREAD

**Issue by jljouannic** [cfpio/callForPapers#134]
When event has nothing but an `id` in database, trying to access the app for this `id` gives various exceptions depending on the missing config parameter.

**Comment by jljouannic** [comment]
if  `date`, `decision_date`… are `NULL` in database:
```
java.lang.NullPointerException: null
	at java.util.Calendar.setTime(Calendar.java:1770)
	at org.apache.commons.lang.time.FastDateFormat.format(FastDateFormat.java:819)
	at io.cfp.dto.ApplicationSettings.<init>(ApplicationSettings.java:47)
	at io.cfp.controller.ApplicationController.getApplicationSettings(ApplicationController.java:69)
	at io.cfp.controller.ApplicationController$$FastClassBySpringCGLIB$$62265d43.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
	at io.cfp.controller.ApplicationController$$EnhancerBySpringCGLIB$$485f0f35.getApplicationSettings(<generated>)
```

if `open` is `NULL` in database:
```
org.springframework.orm.jpa.JpaSystemException: Null value was assigned to a property of primitive type setter of io.cfp.entity.Event.open; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of io.cfp.entity.Event.open
```
